config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'archive/index'
  resources :entries
  root to:"entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :category
    validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: true
    def day
        self.created_at.strftime("%b %e, %Y")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archive/index.html.erb
<div class="columns is-centered mt-6">
    <div class="columns is-half">
        <% @entries.each do |day, entries| %>
            <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">Entries for <%= day%></h3>

            <% entries.each do |entry| %>
                <%= link_to entry_path(entry) do %>
                    <div class="card">
                        <div class="card-content">
                            <strong><%= entry.meal_type %></strong><br/>
                            <%= entry.calories %> calories,
                            <%= entry.proteins %> g proteins,
                            <%= entry.carbohydrates %> g carbs,
                            <%= entry.fats %> g fat,
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type %>
    <%= form.text_field :meal_type %>
  </div>

  <div class="field">
    <%= form.label :calories %>
    <%= form.text_field :calories %>
  </div>

  <div class="field">
    <%= form.label :proteins %>
    <%= form.number_field :proteins %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates %>
    <%= form.number_field :carbohydrates %>
  </div>

  <div class="field">
    <%= form.label :fats %>
    <%= form.number_field :fats %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect {|u| [u.title, u.id]}, {} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<% content_for :title do %>
  Food &ndash; <% DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="columns is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title"><%= entry.meal_type %> - <%= entry.category.title if entry.category.present? %></p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories </p>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> grams of proteins </p>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> grams of carbohydrates </p>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> grams of fat </p>
            <p class="italic">Logged <% time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'Show', entry, class: "card-footer-item" %>
          <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archive_index_path, class: "button is-link is-outlined is-centered" %>
</div>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p>
  <strong>Meal type:</strong>
  <%= @entry.meal_type %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @entry.calories %>
</p>

<p>
  <strong>Proteins:</strong>
  <%= @entry.proteins %>
</p>

<p>
  <strong>Carbohydrates:</strong>
  <%= @entry.carbohydrates %>
</p>

<p>
  <strong>Fats:</strong>
  <%= @entry.fats %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notication is-link is-light"><% notice %></div>
    <% end %>

    <% if alert.present? %>
      <div class="notication is-danger is-light"><% alert %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-info is-small">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <span class="has-textweight-bold is-size-4 ml-4">Food</span>
          <% end %>
          </a>
          <span class="navbar-burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
                <%= link_to "Create new entry", new_entry_path, class: "button is-success" %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Food
        <% end %>
      </h1>
      
    </div>
  </div>

 
</section>